#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           myServo,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           myMotor,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorVex393_MC29, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Updated 9/6/2018  Joel Graber

task main {
	while (true) {
		motor[leftMotor] = vexRT[Ch1]+vexRT[Ch2];
		motor[rightMotor] = vexRT[Ch1]-vexRT[Ch2];
		motor[
	}
}
